### ISSUE TITLE
Missing `classnames` dependency

### ISSUE THREAD

**Issue by dylanfprice** [react-component/cascader#219]
`classnames` is [imported in the Checkbox component](https://github.com/react-component/cascader/blob/master/src/OptionList/Checkbox.tsx#L2)

But it is not present under `dependencies` in `package.json`.

This causes issues when installing under [yarn 2](https://yarnpkg.com/) which is very strict about dependencies.

I was able to work around by adding this to my `.yarnrc.yml`:
```
packageExtensions:
  rc-cascader@*:
    dependencies:
      classnames: "*"
```
